dwango/mastodon

app/models/user.rb

:art: where -> find_by

---

app/assets/javascripts/components/emoji.jsx

I want use nicoru as emoji!!!!!!
I also implemented a rotation function.

Implement :nicoru:

---

app/assets/javascripts/components/emoji.jsx

fix nicoru unlimited.

---

app/assets/javascripts/components/locales/ja.jsx

8 results 件とは... 本家に出せばいい気がするけどなんとなく。

sayonara results

---

app/assets/javascripts/components/actions/compose.jsx

Follow original specification.
Sorry for missed coding 🙇 
@masarakki  Please review and merge this

Fix at-pizza command implementation

---

app/controllers/settings/oauths_controller.rb
app/models/user.rb
app/views/api/v1/accounts/show.rabl
app/views/settings/oauths/show.html.haml
config/locales/simple_form.en.yml
config/locales/simple_form.ja.yml
config/navigation.rb
config/routes.rb
db/migrate/20170424040425_add_hide_oauth_flag.rb
db/schema.rb
spec/models/user_spec.rb

oauth-settings

---

app/assets/javascripts/components/actions/compose.jsx
app/assets/javascripts/components/features/compose/components/compose_form.jsx
app/assets/javascripts/components/features/compose/containers/compose_form_container.jsx
app/assets/javascripts/components/features/ui/components/onboarding_modal.jsx
app/assets/javascripts/components/reducers/compose.jsx

We can :nicoru: only one click or tap!

add insert nicoru button

---

README.md

add the link in README.md to "http://dic.nicovideo.jp/friends.nico"

add the doc.nicovideo link in README.md

---

app/assets/stylesheets/containers.scss

This reverts commit 23078e19131c48ea9abd768964060ec753f274bd.

Revert "fix-for-safari"

---

app/javascript/mastodon/features/compose/components/announcements.js

Show a user support information to below the new toot form.
@masarakki Please review this :nicoru:

Add an announcement of user support

---

app/controllers/api/v1/statuses_controller.rb
app/controllers/api/v1/votes_controller.rb
app/javascript/mastodon/actions/compose.js
app/javascript/mastodon/actions/enquetes.js
app/javascript/mastodon/components/status_content.js
app/javascript/mastodon/features/compose/components/compose_form.js
app/javascript/mastodon/features/compose/containers/compose_form_container.js
app/javascript/mastodon/features/enquete/components/enquete_button.js
app/javascript/mastodon/features/enquete/components/enquete_content.js
app/javascript/mastodon/features/enquete/components/enquete_inputs.js
app/javascript/mastodon/features/enquete/containers/enquete_button_container.js
app/javascript/mastodon/features/enquete/containers/enquete_content_container.js
app/javascript/mastodon/features/enquete/containers/enquete_inputs_container.js
app/javascript/mastodon/locales/ja.json
app/javascript/mastodon/reducers/enquetes.js
app/javascript/mastodon/reducers/index.js
app/javascript/mastodon/reducers/statuses.js
app/javascript/styles/custom.scss
app/javascript/styles/enquete/enquete.scss
app/lib/enquete_extension.rb
app/lib/formatter.rb
app/models/status.rb
app/services/post_status_service.rb
app/views/api/v1/statuses/_show.rabl
app/workers/enquete_result_toot_worker.rb
config/initializers/sidekiq.rb
config/routes.rb
db/migrate/20170816070646_add_enquete_to_statuses.rb
db/schema.rb

Implement enquete feature on friends.nico :sparkles:

---

app/workers/enquete_result_toot_worker.rb

このような感じで、投票トゥートだけブーストされてきても結果がわかるようになったりします

in_reply_toをアンケート結果トゥートに追加

---

app/javascript/styles/nico/favourite_tags.scss

Fix lock icon's vertical position.

Fix favourite tags lock icon position

---

app/controllers/api/v1/favourite_tags_controller.rb
app/views/api/v1/favourite_tags/create.rabl
config/routes.rb
spec/controllers/api/v1/favourite_tags_controller_spec.rb

add `create` / `remove` favourite tag API for application.
- `POST /api/v1/favourite_tags`
- `DELETE /api/v1/favourite_tags/:id`

Add create and remove favourite tag API

---

app/javascript/mastodon/features/compose/components/favourite_tags.js
app/javascript/mastodon/locales/defaultMessages.json
app/javascript/mastodon/locales/en.json
app/javascript/mastodon/locales/ja.json
app/views/settings/favourite_tags/index.html.haml
config/locales/en.yml
config/locales/ja.yml
config/navigation.rb

お気に入りタグ機能のロケール対応

---

app/javascript/mastodon/components/status.js

チュートリアル終了後でもリプライボタンが無効化されているバグを修正しました

Fix custom tutorial

---

app/lib/friends/profile_emoji_extension.rb

Fix profile emoji bugs

---

app/views/settings/favourite_tags/index.html.haml
app/views/settings/highlight_keywords/index.html.haml

Improvement of delete button of favourite_tags and highlight_keywords

---

app/javascript/mastodon/features/compose/components/announcements.js

Add announcement for friends.nico @ TOKYO

---

app/models/status.rb
app/services/fan_out_on_write_service.rb

```sql
SELECT "statuses".* FROM "statuses" INNER JOIN "statuses_tags" ON "statuses_tags"."status_id" = "statuses"."id" LEFT OUTER JOIN "accounts" ON "accounts"."id" = "statuses"."account_id" WHERE (statuses.reblog_of_id IS NULL) AND "statuses_tags"."tag_id" = $1 AND "statuses"."visibility" IN (0, 1) AND "accounts"."silenced" = $2 ORDER BY "statuses"."id" DESC  [["tag_id", 0], ["silenced", "f"]]
```

show-unlisted-hashtags
